### ISSUE TITLE
AttributeError: 'DataParallel' object has no attribute 'pca'

### ISSUE THREAD

**Issue by taobiaoli** [almazan/deep-image-retrieval#5]
when i run the command.
python -m dirtorch.test_dir --dataset Oxford5K --checkpoint Resnet-101-AP-GeM.pt/Resnet-101-AP-GeM.pt --whiten Landmarks_clean --whitenp 0.25 --gpu 0

=> loading checkpoint 'Resnet-101-AP-GeM.pt/Resnet-101-AP-GeM.pt' (current_iter 296)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/image_retrieval/Deep_Image_Retrieval/deep-image-retrieval/dirtorch/test_dir.py", line 299, in <module>
    net = load_model(args.checkpoint, args.iscuda)
  File "/home/image_retrieval/Deep_Image_Retrieval/deep-image-retrieval/dirtorch/test_dir.py", line 241, in load_model
    net.pca = checkpoint.get('pca', net.pca)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 537, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'pca'

**Comment by almazan** [comment]
Thanks a lot for pointing this out.

I have just pushed a fix that should addresses this bug. Let me know if you still have problems running the code.
